# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentStripe < Formula
  desc "Read-only Stripe CLI for AI agents"
  homepage "https://github.com/simonperryman/agent-stripe"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.1/agent-stripe_1.0.1_darwin_amd64.tar.gz"
      sha256 "4e7a3af7871edc171c9dfabc72b9d9a4930202006a4315968ca2bca791ea5830"

      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.1/agent-stripe_1.0.1_darwin_arm64.tar.gz"
      sha256 "24d6127617b528269693baac00f38367eed9afeace252d782d75d7955a45fc6a"

      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.1/agent-stripe_1.0.1_linux_amd64.tar.gz"
      sha256 "60b4be778582c4bf59aa39601ed903565b7e8ea5707fe9470fbbdc9c4525663b"
      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.1/agent-stripe_1.0.1_linux_arm64.tar.gz"
      sha256 "73af3a4c2ba4d6e7b2514782fa5bafed19ac70d4823424c9391d0092882a66e6"
      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
  end

  def caveats
    <<~EOS
      agent-stripe stores Stripe API keys in your OS keychain.
      First-time setup:
        agent-stripe account add default --form --default
    EOS
  end

  test do
    system "#{bin}/agent-stripe", "usage"
  end
end
