# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentStripe < Formula
  desc "Read-only Stripe CLI for AI agents"
  homepage "https://github.com/simonperryman/agent-stripe"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.0/agent-stripe_1.0.0_darwin_amd64.tar.gz"
      sha256 "a8f7ffe3182ee77c234f20dc39f5212313adbd550fd0de13fb741a9adad9ab8f"

      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.0/agent-stripe_1.0.0_darwin_arm64.tar.gz"
      sha256 "0a6d841b29ca574bd4cfc91c4c0028898c4fbcd0ee4639b740aa4028bcb1412d"

      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.0/agent-stripe_1.0.0_linux_amd64.tar.gz"
      sha256 "7562b1bd8925a6ec0a25f775bbbc3a48d922f608127df5212d693e9eb8a0ff09"
      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimonPerryman/agent-stripe/releases/download/v1.0.0/agent-stripe_1.0.0_linux_arm64.tar.gz"
      sha256 "b572a592bc7db4ff038c4c80b0e6b8772b4e42f7fefceee9e45c232068f2b6b2"
      define_method(:install) do
        bin.install "agent-stripe"
      end
    end
  end

  def caveats
    <<~EOS
      agent-stripe stores Stripe API keys in your OS keychain.
      First-time setup:
        agent-stripe account add default --form --default
    EOS
  end

  test do
    system "#{bin}/agent-stripe", "usage"
  end
end
